---
title: "home1"
author: "Arya Candra"
date: "`r Sys.Date()`"
output: html_document
---

## Well-Being Sebagai Ukuran Pembangunan Berkelanjutan

SDGs mendorong negara-negara yang menandatangani kesepakatan tersebut untuk menyediakan data terkait dengan capaian pembangunan berkelanjutan sesuai dengan kondisi masing-masing negara. Indonesia juga mengalami pertumbuhan yang cepat dalam penyediaan data di seluruh goals dan menambah rincian pada level regional. Bahkan dengan adanya pandemi Covid-19 tidak menyurutkan langkah bangsa ini untuk melengkapi data dalam upaya mempertajam evaluasi pembangunan berkelanjutan. Aplikasi ini merupakan salah satu upaya untuk melengkapi data kualitas hidup yang lebih komprehensif sesuai dengan tujuan SDGs.

Ukuran kesejahteraan merupakan suatu keniscayaan karena upaya evaluasi dan perencanaan pembangunan ekonomi perlu beranjak pada ukuran yang dapat dipercaya dan terbanding antarwaktu dan antarwilayah. Commision on Measurement of Economic Performance and Social Progress (CMEPSP) menyampaikan ukuran well-being, yang muncul karena dipicu oleh krisis finansial yang parah pada tahun 2008. Karena krisis ini, sangat penting untuk melakukan perubahan dalam sistem pengukuran indikator statistik yang tepat. Mereka berpendapat bahwa sudah saatnya pengukuran beralih dari ukuran produksi ekonomi ke ukuran kesehatan. Hal ini tidak berarti PDB tidak diperlukan, namun harus ditingkatkan kepada ukuran yang berkaitan dengan kesejahteraan masyarakat. Dengan kata lain, sistem statistik telah berubah, dari hanya mengukur aktivitas ekonomi (market activities) menjadi kesejahteraan masyarakat dan keberlanjutannya (sustainability). Indikator statistik tersebut menggabungkan elemen non-ekonomi dan ekonomi (material living-standard) ke dalam ukuran multidimensi (Stiglitz & Sen, 2009).

Ketertarikan internasional dalam penelitian ukuran kesejahteraan yang multidimensi ini meningkat pesat beberapa tahun terakhir karena dorongan inisiatif "Beyond GDP". Boarini et al. (2014) dan Durand (2015) meneliti pengukuran well-being dan kemajuan di beberapa negara dengan different stages of development. PDB memiliki keterbatasan dalam mengukur welfare. Hal ini dikarenakan pertumbuhan ekonomi tidak sebanding dengan pertumbuhan pendapatan rumah tangga dan pertumbuhan tersebut menutupi inequalities in economic resources and opportunities antara orang-orang dan rumah tangga dengan karakteristik yang berbeda. Selain itu, PDB dapat berkorelasi negatif, utamanya terhadap indikator kinerja lingkungan, misalnya polusi udara.

Dalam arti sempit well-being dinyatakan sebagai kesejahteraan. Barrington-Leigh & Escande (2018) menyatakan bahwa well-being merupakan ukuran kesejahteraan yang multidimensi dan lebih komprehensif dari sisi sosial, psikologis dan lingkungan. OECD (2011) menyatakan well-being tidak hanya menyangkut aspek ekonomi (pendapatan). Uang bukanlah segalanya yang bisa menjamin well-being. Ada banyak aspek non-ekonomi yang membentuk well-being seseorang seperti kenyamanan tempat tinggal, kualitas lingkungan hidup, kebebasan melakukan kegiatan politik dan sosial, serta subjektivitas seseorang dalam memaknai kehidupannya. Pengukuran subjektif lebih merepresentasikan kesejahteraan (Angner, 2011). Oleh karena itu well-being dapat dikembangkan menjadi ukuran kesejahteraan yang lebih luas sesuai dengan kondisi negara masing-masing.